# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='地址名称'),
        ),
    ]
